{
  "Home": true,
  "About": true,
  "Benefits": true,
  "Downloads": true,
  "FAQs": true,
  "Blog": true,
  "Referral Program": true,
  "Contact": true,
  "Support": true,
  "login": true,
  "signup": true,
  "Decentralized Bitcoin Exchange:": true,
  "Your keys, your crypto": true,
  "Whitepaper ": true,
  "Start Trading Now": true,
  "Fast Transactions": true,
  "NightTrader offers lightning-fast transactions and high scalability, addressing common performance issues in other exchanges. The only DEX in the world to support high speed Bitcoin trading.": true,
  "Unmatched Security": true,
  "Unlike central exchanges prone to hacks, on NightTrader you hold your keys giving you full control over your funds. During trades, NightTrader uses a joint account with signature-hashes to route debt with a locktime back to the user with threshold signatures on the backend split between nodes all over the world. The one and only exchange to use this ultra-secure method!": true,
  "Cost-Effective": true,
  "NightTrader maintains competitive trading fees, making it more affordable for users seeking efficient cryptocurrency exchange solutions. It can do this because half-signed transactions can get routed on multiple high speed trades by the decentralized system of nodes that validate it before it is broadcasted and cleared.": true,
  "what is nighttrader": true,
  "Unparalleled Innovation in Cryptocurrency Trading": true,
  "The first open source decentralized exchange that supports all types of coins including Bitcoin, UTXO style currencies(Litecoin, Bitcoin cash, etc), Ethereum tokens and more! All of this without using 'middle coins', gimmicks, wrapped tokens or anything else which has shown to not give the user proper security. We care about our users security!": true,
  "Our Mission": true,
  "Reduce fraud in the cryptocurrency space and provide an on- and off-ramp to cryptocurrency markets.": true,
  "Our Vision": true,
  "Create a platform that safely integrates cryptocurrency into escrow services and a currency exchange, while providing unprecedented security and reliability for professional traders and citizens alike.": true,
  "The Future of Cryptocurrency Exchange": true,
  "By addressing critical pains in the crypto space, NightTrader.Exchange not only safeguards potential losses but also revolutionizes e-commerce and cryptocurrency trading, setting new standards in the industry.": true,
  "about us": true,
  "Deep dive into the technology": true,
  "Multisignature DEX: (User holds one key, nodes hold the other)": true,
  "Proof of reserves. Accounts publicly verified. Full transparency with privacy in tact": true,
  "Uses threshold keys(a single key that is actually a giant multisignature) allowing for decentralized consensus": true,
  "Open source! Run JavaScript locally with a few clicks. Audit the entire front end.": true,
  "Provides Deadmans Switch(checklocktimeverify) & backup solution in case of a Force Majeure": true,
  "Protected from hacking phishing and supply chain attacks": true,
  "Supports Bitcoin, Ethereum and altcoins and can even support Monero": true,
  "High speed trading! Uses signature hashes to route debts between users.": true,
  "NightTrader was proposed in 2014 so it has been 10 years in the making! See what all the talk is about and visit our community on social media.": true,
  "Follow us": true,
  "Clear Advantages": true,
  "Compare to competition": true,
  "Unlike atomic trades, these trades are much faster and cheaper": true,
  "Automated market makers(AMMs) don't support native Bitcoin or use risky wrapped assets and don't support spot exchange. NightTrader does all this and more!": true,
  "Wrapped coins and wrapped coin networks don't give the user a key. So their multisignature may not be real or eventually compromised. If their funds are frozen users have no defense. NightTrader has no such problem because funds are timelocked back to the users.": true,
  "ZK rollups are great for spot exchange however they also lack Bitcoin support and support for other coin types. NightTrader can in theory support almost any type of coin while giving high levels of security.": true
}



{
  "Double Deposit Escrow can also be used by our partners for the ability to transact peer to peer. This works as a perfect crypto on ramp and the only way to on ramp fully decentralized and securely without a single middle man or arbiter. It could be combined in conjunction with other services.": true,
  "Is NightTrader perfect? There is still a small risk during a trade if all the nodes are compromised however the risk is extremely low and the users balance(other than the trade) would still be in tact. Also if the exchange gets lot's of users and volume things like atomic trades and rollups and AMMs could also be used.": true,
  "Simply the best!": true,
  "Discounts, Referrals, Recovery": true,
  "Market Maker Discounts": true,
  "Provide Liquidity and make our Markets to receive special discounts on trading.": true,
  "Referrals": true,
  "Our 5 Tier Referral System give 10% commission up to 5 Levels down. Make a passive income cash cow with inviting your friends. Find out": true,
  "more here!": true,
  "Wallet Recovery System": true,
  "Unlike most competitors, NightTrader provides a unique wallet recovery option, ensuring users never lose access to their funds. ": true,
  "benefits ": true,
  "Other Key Features & Benefits": true,
  "Simplicity": true,
  "User-friendly app and account creation, intuitive also for casual bettors.": true,
  "Highly advanced user interface": true,
  "The platform has advanced charting, a sleek design and many great trading features giving the same feel of a top tier exchange.": true,
  "Non-Custodial": true,
  "Yours truly. Hold your own key to your crypto.": true,
  "Proof of funds": true,
  "Every account has their dedicated wallets. No Mixing with others. Proof of funds made easy.": true,
  "Start Trading Now!": true,
  "documents ": true,
  "Download & Read Our Documents": true,
  "White": true,
  "Paper": true,
  "download": true,
  "Knowledgebase": true,
  "Frequently Asked Questions": true,
  "Below are some frequently asked questions.": true,
  "general": true,
  "Exchange": true,
  "How is this different?": true,
  "Even the best DEXes don't support native Bitcoin or do so using unsafe wrapped assets. Others may claim security but actually use a multisig without giving the user a key. NightTrader is different, you get a key and control your entire balance and trades are routed using a large network of nodes.": true,
  "What is Multisignature?": true,
  "Multisignature, often referred to as 'multisig', is a security feature used in cryptocurrency transactions that requires multiple private keys to authorize a transaction. In NightTrader Exchange's context, it's a crucial component of their decentralized multi-signature exchange. Multisig enhances security by distributing control among multiple parties, reducing the risk of unauthorized access or theft. For example, a 2-of-3 multisig setup would require any two out of three designated keys to approve a transaction. This technology not only protects users' funds but also enables NightTrader to offer non-custodial trading, allowing users to maintain full control of their assets while trading on the platform.": true,
  "What is Decentralised?": true,
  "Decentralized refers to a system that operates without a central authority or single point of control. Instead of relying on a centralized entity to manage transactions and hold funds, NightTrader's decentralized platform distributes control among its users. This approach enhances security by eliminating the risk of a single point of failure, which is often a vulnerability in centralized exchanges. In NightTrader's decentralized system, users maintain full control of their assets through non-custodial trading, meaning they retain possession of their private keys and funds at all times. This decentralized structure not only increases security but also promotes transparency and reduces the risk of manipulation or censorship, aligning with the core principles of blockchain technology.": true
}

{
  "Who are NightTraders nodes?": true,
  "The nodes in NightTrader can be anyone! The users themselves, dedicated community members, investors and reliable individuals in the cryptocurrency community. These nodes sign the second half of the transaction validating the trades. Each one checks transactions and data independently verifying trades go where they are supposed to. They all sign part of an elliptical curve combining into a single signature which is also called a 'threshold signature'. This is how NightTrader maintains decentralization.": true,
  "What happens if the exchange vanishes?": true,
  "Unlike other exchanges, NightTrader uses something called 'checklocktimeverify' also called 'dead mans switch'. This is native to Bitcoin which allows a time lock that after some time the ownership of funds changes. Since NightTrader nodes hold the second key, if they don't sign off on a trade or withdrawal there is a time lock that after a certain number of months, the funds safely return to the user automatically. This is built into Bitcoin so no trust is required, the deposit account script is there for you to see on the blockchain and validate! Imagine if a large exchange like Binance disappeared, what could the users do? NightTrader is different, you keep control of your funds at all times.": true,
  "How do I create a account?": true,
  "To create an account on my.nighttrader.exchange, start by visiting the website and clicking on the 'Register NightTrader Account' option. You'll need to provide a valid email address or bitmessage address, and create a strong password for your account. Once you've entered this information, you'll be prompted to verify your email address. After verification, you'll have access to your new NightTrader account. It's important to note that NightTrader uses a non-custodial system, meaning you'll maintain full control of your assets. For enhanced security, consider enabling two-factor authentication (2FA) and carefully storing your account recovery information in a safe place.": true,
  "How do I make a deposit?": true,
  "To make a deposit on NightTrader Exchange, first ensure you have created your account. Then, log in to your NightTrader account and navigate to the 'Wallet' section. Select the cryptocurrency you wish to deposit (e.g., Bitcoin, Ethereum) and generate a unique deposit address for that specific cryptocurrency. Use this address to send funds from your external wallet or another exchange. Remember, NightTrader uses a non-custodial system, so your funds remain under your control even after deposit. Always double-check the deposit address before sending any funds, and be aware that transaction times may vary depending on the cryptocurrency network's current congestion and the fee you choose.": true,
  "What are timelocks for?": true,
  "Timelocks in NightTrader are a crucial security feature that enhances the functionality of multisignature transactions. They work by setting a specific time period during which funds cannot be moved or accessed without meeting certain conditions. In NightTrader's implementation, timelocks are used in conjunction with multisignature wallets to create a robust escrow system. This system allows for the creation of time-bound contracts where funds are locked until a predetermined future date or block height. Timelocks can prevent premature withdrawal of funds, protect against theft or unauthorized access, and enable more complex transaction scenarios. For example, in NightTrader's escrow system, timelocks ensure that funds remain secure until all parties have fulfilled their obligations or until a predetermined settlement date has been reached. This mechanism enhances trust, security, and flexibility in decentralized trading environments, allowing for sophisticated financial arrangements without the need for intermediaries.": true,
  "How do I trade?": true
}

{
  "To trade on NightTrader Exchange, first ensure you have created an account and deposited funds. Then, navigate to the trading section of the platform. Select the trading pair you wish to interact with (e.g., BTC/ETH). You'll see the current market prices and order book. To place an order, choose whether you want to buy or sell, enter the amount you wish to trade, and set your desired price. NightTrader uses a non-custodial system, so your funds remain under your control during the trading process. The platform's unique multi-signature technology ensures secure transactions, while the double deposit escrow system provides additional protection for more complex trades. Remember to review your order details carefully before confirming, as cryptocurrency transactions are typically irreversible.": true,
  "Our Blog": true,
  "Latest Articles": true,
  "go to our Substack ": true,
  "get in touch": true,
  "Contact Us": true,
  "Have any question? Write to us and we’ll get back to you shortly.": true,
  "Menu": true,
  "About": true,
  "Benefits": true,
  "Referral Program": true,
  "Support": true,
  "PAPERS": true,
  "White Paper": true,
  "legal": true,
  "Privacy Policy": true,
  "Terms & Conditions": true,
  "Cookie Policy": true,
  "Newsletter": true
}

{
  "5 Tiers": true,
  "Maximize": true,
  "5 Tier Referral Program:": true,
  "Your Friends, Your Earnings!": true,
  "Start Referrals Now!": true,
  "5 Tier Rewards": true,
  "Welcome to NightTrader Exchange, where our innovative 5-tier referral system rewards you for growing our community. Climb the ranks and increase your earnings with each new tier!": true,
  "How it works": true,
  "Our referral system is designed to reward you for bringing new traders to the platform. As you progress through the tiers, you'll earn a percentage of the trade fees generated by your referrals and their subsequent referrals.": true,
  "Invite your friends": true,
  "Generate a cash cow with your friends. Nobody offers this much as we do!": true,
  "Start making cash:": true,
  "The 5 Tiers": true,
  "Start as CryptoKnight by directly referring someone using your invite code. Note: You only earn when your referrals trade": true,
  "CryptoKnight (Tier 1)": true,
  "Earnings: 60% of 1/10th of trade fees generated by your direct referrals": true,
  "CryptoBaron (Tier 2)": true,
  "Earnings: 24% of trade fees from your referrals' referrals": true,
  "CryptoEarl (Tier 3)": true,
  "Earnings: 9.6% of trade fees from third-level referrals": true,
  "CryptoDuke (Tier 4)": true,
  "Earnings: 3.84% of trade fees from fourth-level referrals": true,
  "CryptoPrince (Tier 5)": true,
  "Earnings: 2.56% of trade fees from fifth-level referrals": true,
  "Overview": true,
  "Earnings Breakdown": true,
  "How to ": true,
  "Maximize Your Earnings": true,
  "Invite Active Traders:": true,
  "Encourage Referrals:": true,
  "Climb the Tiers:": true,
  "Stay Engaged:": true,
  "Act now": true,
  "Start Your Journey": true,
  "Become a CryptoKnight & start earning!": true,
  "Get your unique invite code to share with traders.": true,
  "Remember, your success grows with our community!": true,
  "Experience the power of our 5-tier referral system.": true,
  "Part 1": true,
  "Part 2": true,
  "Part 3": true,
  "What is the NightTrader Exchange referral system?": true,
  "The NightTrader Exchange referral system is a 5-tier program that rewards users for bringing new traders to the platform. As you progress through the tiers, you earn a percentage of the trade fees generated by your referrals and their subsequent referrals.": true,
  "How do I join the referral program?": true,
  "To join the referral program, simply sign up for a NightTrader Exchange account and start referring new users with your unique invite code.": true,
  "How do I become a CryptoKnight?": true,
  "You become a CryptoKnight by directly referring someone to NightTrader Exchange using your invite code.": true,
  "Do I earn rewards if my referrals don't trade?": true,
  "No, you only earn rewards when your referrals actively trade on the platform.": true,
  "How do I progress to higher tiers?": true,
  "To progress to higher tiers, your referrals must also refer new users. For example, to become a CryptoBaron, your direct referrals must have their own referrals.": true,
  "Can I earn from multiple tiers simultaneously?": true,
  "Yes, you can earn from multiple tiers simultaneously as long as you have referrals at different levels.": true,
  "How are the earnings calculated for higher tiers?": true,
  "Higher tiers earn a percentage of the remaining trade fees after lower tiers have been paid out. For example, CryptoBarons earn 24% of the fees remaining after CryptoKnights have been paid.": true,
  "Is there a limit to how many referrals I can have?": true,
  "There is no limit to the number of referrals you can have at any tier.": true,
  "How can I maximize my earnings in the referral program?": true,
  "To maximize your earnings: Invite active traders, encourage your referrals to refer others, aim to climb to higher tiers and stay engaged with your referral network.": true,
  "How often are referral rewards paid out?": true,
  "First every week after we do a maintaince usually on sunday. Later with more users it will be more frequently.": true,
  "Can I track my referral earnings?": true,
  "Yes, you should be able to track your referral earnings through your NightTrader Exchange account dashboard. For detailed information, please check the platform or contact support.": true,
  "Faq": true,
  "Requirement: At least one direct referral": true,
  "Requirement: Your direct referrals must have their own referrals": true,
  "Requirement: Your CryptoBaron referrals must have their own referrals": true,
  "Requirement: Your CryptoEarl referrals must have their own referrals": true,
  "Requirement: Your CryptoDuke referrals must have their own referrals": true,
  "Your earnings depend on your referrals' trading activity.": true,
  "Help your referrals understand the system so they can refer others.": true,
  "The higher your tier, the more levels of referrals you can earn from.": true,
  "Keep in touch with your referrals to maintain an active network.": true
}