import Button from "@/components/ui/Button.tsx";

import Relume from "@/assets/relume.svg";

export default function AffiliatePage() {
  const unlockItems = [
    {
      title: "Enjoy a steady stream of passive income.",
      description: "Earn competitive commissions based on user trading activity.",
    },
    {
      title: "Partner with a trusted exchange for success.",
      description: "Monitor your earnings and referrals effortlessly.",
    },
    {
      title: "No limits on how much you can earn.",
      description: "Receive your commissions quickly and reliably.",
    }
  ];
  
  return (
    <>
      <div className={"flex flex-col md:flex-row items-center gap-5 md:gap-20 py-14 md:py-28 px-8 md:px-16"}>
        <div className={"flex flex-col gap-2 gap-4 w-full"}>
          <p className={"text-base font-semibold"}>Earn</p>
          <p className={"text-3xl md:text-5xl font-bold"}>Join Our Lucrative Affiliate Program Today</p>
        </div>
        <div className={"flex flex-col gap-4 md:gap-8 w-full"}>
          <p>Our 5 Tier Referral System gives 10% commission up to 5 Levels down. Make  a passive income cash cow with inviting your friends.</p>
          <div>
            <Button variant={"outlined"}>Sign Up</Button>
          </div>
        </div>
      </div>
      <div className={"flex flex-col md:flex-row items-center gap-5 md:gap-20 py-7 md:py-28 px-8 md:px-16"}>
        <div className={"flex flex-col gap-4 w-full"}>
          <p className={"text-base font-semibold"}>Earn</p>
          <p className={"text-3xl md:text-5xl font-bold"}>Monetize Your Network</p>
          <p className={"text-base md:text-lg"}>Our affiliate program allows you to earn a percentage of trading fees from users you refer. It's an easy way for influencers and everyday users to monetize their network.</p>
        </div>
        <div className={"w-full aspect-square empty-image"} /> 
      </div>
      <div className={"flex flex-col gap-10 md:gap-20 py-14 md:py-28 px-8 md:px-16"}>
        <div className={"flex flex-col md:flex-row items-center gap-5 md:gap-20"}>
          <div className={"flex flex-col gap-4 w-full"}>
            <p className={"text-base font-semibold"}>Earn</p>
            <p className={"text-3xl md:text-5xl font-bold"}>Unlock Your Earning Potential with NightTrader</p>
          </div>
          <p className={"w-full text-base md:text-lg"}>Join our affiliate program and start earning today! Whether you're an influencer or a regular user, you can
            profit from a percentage of trading fees generated by your referrals. It's a simple way to monetize your
            network while helping others discover the benefits of nighttrader.exchange.</p>
        </div>
        <div className={"flex flex-col md:flex-row gap-6 md:gap-12 justify-between"}>
          {
            unlockItems.map(({ title, description }) => (
              <div
                key={title}
                className={"flex flex-col gap-2 md:gap-6"}
              >
                <Relume className={"size-8 md:size-12"}/>
                <p className={"text-xl md:text-3xl font-bold"}>{title}</p>
                <p className={"text-base"}>{description}</p>
              </div>
            ))
          }
        </div>
      </div>
      <div className={"flex justify-center py-14 md:py-28"}>
        <Button>Sign Up</Button>
      </div>
    </>
  );
}